---
title: "Homework 1, ARFIMA estimation"
output: html_notebook
---

## Libraries
```{r}
library(ggplot2)
library(xts)
library(tseries)
library(dplyr)
library(fracdiff)
library(forecast)
```


## Data input
```{r}
set.seed(11148705)

filepath <- file.path(getwd(), "data", "vix_data.csv")

returns <- read.zoo(filepath, sep = ",", format = "%Y%m%d")

X <- log(as.xts(returns)

dX <- na.trim(diff(X))

head(dX)
```

## Exercise 1 - Plot
We now can plot $X_t$ and the first difference $\Delta X_t$

```{r}
autoplot(X)
autoplot(dX)
```


Autcorellation function
```{r}

autocorr <- function(vector, h) {
  n <- length(vector)
  vec_dem <- vector-mean(vector)
  
  prev <- vec_dem[1:(n-abs(h))]
  subs <- vec_dem[(1+abs(h)):n]
  
  rho_hat <- t(prev)%*%subs / t(vec_dem)%*%vec_dem
  
  
  return(rho_hat) 
} 

sample_acf <- function(series, hs) {
  vec <- as.vector(series)
  
  compute_autocorr <- function(h) autocorr(vec, h) 
  
  ac <- sapply(hs, compute_autocorr)
  
  return(ac)
}
```


The sample autocorrelation

```{r}
acf(X)
acf(dX)
```


It seems that the series $X_t$ is non stationary and hence we should start from $\Delta X_t$

## Excerice 2
```{r}
adf.test(as.ts(X))
adf.test(as.ts(dX))
```


## Exercise 3


```{r}
spectral_dens <- function(X, l) {
  n <- length(X)
  hs <- as.vector((1-n):(n-1))
  

  corrs <- sample_acf(X, hs)
  weights <- sapply(hs, function (h) if (abs(h) < l) 1 - abs(h)/(l+1) else 0)
  
  dens <- function(lambda) {
    cosines <- cos(lambda*hs)
    f_hat <- sum(weights*corrs*cosines)
    return (f_hat / (2*pi))
  }
  
  return (dens)
}
```


```{r}
l <- 33
n <- length(dX)
dens_fn <- spectral_dens(dX, l)

density_space <- seq(0, 2*pi, length.out=n)
estimated_dens <- sapply(density_space, dens_fn)

df <- data.frame(lambda=density_space, f_estimated_density=estimated_dens)
ggplot(data=df, aes(lambda, f_estimated_density)) + geom_line()
```


## Exercise 4 - Geweke and Porter-Hudak

```{r}
fracGPH <- function(dX, l, verbose=FALSE) {
  n <- length(dX)
  m <- floor(sqrt(n))
  
  dens_fn <- spectral_dens(dX, l)
  
  support_upper <- 2*pi*m/n
  density_space <- seq(0.01, support_upper, length.out=m)
  

  I <- sapply(density_space, dens_fn)
  llambda <- log(2*sin(0.5*density_space))
  
  df <- data.frame(I=I, log_lambda=llambda)
  
  model_fit <- lm(I ~ log_lambda, data=df)
  
  if (verbose) {
    print(summary(model_fit))
    print(anova(model_fit))
  }
  
  d <- -0.5*summary(model_fit)$coefficients[2]
  
  return(d)
}

d <- fracGPH(dX, l, verbose=FALSE)
```


```{r}
d <- fdGPH(dX)$d
d
```

## Exercise 5

```{r}
fit_d <- arfima(as.vector(dX))
fit_d
```









